  
### GET a password by name
GET http://localhost:3333/api/passwords/testnummer2

### GET an unknown password by name
GET http://localhost:3333/api/passwords/Mel


### POST a new password
POST http://localhost:3333/api/passwords
Content-Type: application/json

{
    "name": "testnummer2",
    "value": "super-secret-password!!11"
}

### DELETE a password

DELETE http://localhost:3333/api/passwords/testnummer2

### PATCH a password by name

PUT  http://localhost:3333/api/passwords/testnummer2
Content-Type: application/json

{
    "name":"testnummer2",
    "value":"weristdas"
}
